name: Test Rott.dev

on:
  push:
    branches:
      - "**"

jobs:
  rott:
    name: Rott
    uses: rott-dev/workflows/.github/workflows/rott.yaml@main
    secrets:
      shared_rules_token: ${{ secrets.ROTT_SHARED_RULES_TOKEN }}
      rott_token: ${{ secrets.ROTT_TOKEN }}
